#!groovy
@Library('jenkins-library@master') _
pipeline {
    agent {
        kubernetes {
          yaml"""
apiVersion: v1
kind: Pod
spec:
    containers:
    - name: ansible-slave
      image: codingcoffee/aws
      command: ["cat"]
      imagePullPolicy: Always
      tty: true
"""
        }
    }
    options {
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
        stage('Pull Latest Code') {
            steps {
                container('ansible-slave') {
                    git credentialsId: 'jenkins_github_readonly', branch: 'master', url: 'https://github.com/santasecret/rusty'
                }
            }
        }
        stage('Build') {
            environment {
                RUST_TARGETS="x86_64-unknown-linux-musl"
                CARGO_TARGET_DIR="/cache"
            }
            steps {
                container('ansible-slave') {
                    script {
                        sh '''
                        apk add --no-cache musl-dev
                        '''
                        // cargo build --verbose --target $RUST_TARGETS --release
                    }
                }
            }
        }
        stage('Release') {
            environment {
                AWS_ACCESS_KEY_ID="Q5u3Ts986hBAZ7"
                AWS_SECRET_ACCESS_KEY="6M5TZ3T55N2MHo"
                S3_ENDPOINT_URL="https://minio.codingcoffee.me"
            }
            steps {
                container('ansible-slave') {
                    script {
                        sh '''
                        ./ci/release.sh
                        '''
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                shared_functions.sendGotifyNotification(currentBuild.result)
            }
        }
    }
}
